# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2023-03-21 09:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Категории')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'категорию',
                'verbose_name_plural': 'Категории',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Должность')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='URL')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'должность',
                'verbose_name_plural': 'должности',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('surname', models.CharField(max_length=200, verbose_name='Отчество')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='URL')),
                ('male_or_female', models.BooleanField(default=True, verbose_name='Пол')),
                ('age', models.DateField()),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.Category', verbose_name='Категория')),
                ('pos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.Position', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'сотрудник',
                'verbose_name_plural': 'сотрудники',
                'ordering': ['last_name'],
            },
        ),
    ]
